### ISSUE TITLE
Implement the first version of the four-momentum interface

### ISSUE THREAD

**Issue by szabo137** [szabo137/FourMomentumBase.jl#1]
Following the suggestions made [here](https://indico.cern.ch/event/1292759/contributions/5618592/attachments/2749047/4784364/juliahep2023-interface-20231105.pdf), the first, presumably naive, version of the four-momentum interface needs to be implemented. 

Based on this, a simple array based implementation of the interface should be given as well. 

As an additional reference, check out the table interface in [Tables.jl](https://github.com/JuliaData/Tables.jl).

**Comment by mmikhasenko** [comment]
Do you have the first, naive version already? - do you want ot have as a part of this package of extra one?

I'd like to experiment with [FourVectors.jl](https://github.com/mmikhasenko/FourVectors.jl), might give a try to the interface

**Comment by szabo137** [comment]
Sure, this should do the trick:

```julia
using FourMomentumBase
using FourVectors

# implementing the cartesian interface
FourMomentumBase.coordinate_system(::FourVector) = FourMomentumBase.EXYZ()
FourMomentumBase.px(mom::FourVector) = mom.x
FourMomentumBase.py(mom::FourVector) = mom.y
FourMomentumBase.pz(mom::FourVector) = mom.z
FourMomentumBase.energy(mom::FourVector) = mom.E
```

Then, the accessors are available, e.g.

```julia
x,y,z,t = [1, 2, 3, 4.0]
v = FourVector(x,y,z; t=t)

cth,phi = sphericalangles(v)
@assert FourMomentumBase.cos_theta(v) == cth
@assert FourMomentumBase.azimuthal_angle(v) == phi
```
The list of accessor functions is given here:

```julia
FourMomentumBase.FOURMOMENTUM_GETTER_FUNCTIONS
```

BTW: the package is not registered yet, therefore, you need to install it via the URL: 

```julia
import Pkg
Pkg.add(url="https://github.com/szabo137/FourMomentumBase.jl.git")
```

**Comment by szabo137** [comment]
Since the original issue is solved, I will close this here. If there are some more questions, please open a separate issue.
